version: '3'

services:
  app:
    build: ./frontend
    ports:
      - 5001:5000
    volumes:
      - /usr/src/app
    depends_on:
      - api

  backend:
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - /home/src/api
